run:
  timeout: 5m
  modules-download-mode: readonly
  # not our current version, but we need to wait until this supports 1.18
  # https://github.com/golangci/golangci-lint/issues/2649
  go: "1.17"

issues:
  # Enable all checks (which was as default disabled e.g. comments).
  exclude-use-default: false

  exclude-rules:
    # Documenting comments are not required except on packages.
    - linters:
        - golint
      text: exported (function|method) .*? should have comment or be unexported
    - linters:
        - golint
      text: exported const .*? should have comment (\(or a comment on this block\) )?or be unexported
    - linters:
        - golint
      text: exported type .*? should have comment or be unexported
    # Stylecheck checks if at least one file has package comment but it's not required on all of them.
    - linters:
        - golint
      text: package comment should be of the form "Package .*? ..."
    - linters:
        - revive
      text: package-comments
    - linters:
        - stylecheck
      text: ST1000
    - linters:
        - gocritic
      text: whyNoLint

  # Value 0 means show all.
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages,
    # it's a comma-separated list of prefixes.
    local-prefixes: github.com/OpenSLO/oslo
  golint:
    min-confidence: 0
  govet:
    # Report about shadowed variables.
    check-shadowing: true
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - style
  exhaustive:
    # In switch statement treat label default: as being exhaustive.
    default-signifies-exhaustive: true
  misspell:
    locale: US
  forbidigo:
    forbid:
      - ^ioutil\..*$ # Package ioutil is deprecated.
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/OpenSLO/oslo) # Groups all imports with the specified Prefix.
  revive:
    rules:
      - name: package-comments
        severity: ok
linters:
  # Please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint.
  disable-all: true
  enable:
    # All linters from list https://golangci-lint.run/usage/linters/ are specifed here and explicit enable/disable.
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - varcheck
