builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/oslo
    binary: ./bin/oslo
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - -X main.version={{.Version}}

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}_{{ .Mips }}{{ end -}}

brews:
  - name: oslo
    tap:
      owner: OpenSLO
      name: homebrew-OpenSLO
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/OpenSLO/oslo
    install: bin.install "bin/oslo"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Command line tool for working with OpenSLO"
    license: "Apache-2.0"
