version: 2
project_name: oslo

builds:
  - main: ./cmd/oslo
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "{{ .ProjectName }}"

archives:
  - formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}.sha256"
  algorithm: sha256

release:
  make_latest: false
  draft: true
  replace_existing_draft: false
  prerelease: auto
  github:
    owner: OpenSLO
    name: oslo

brews:
  - name: "{{ .ProjectName }}"
    tap:
      owner: OpenSLO
      name: homebrew-OpenSLO
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/OpenSLO/oslo
    install: |
      bin.install Dir['{{ .ProjectName }}-{{ .Version }}-*'].first()  => "{{ .ProjectName }}"
    test: |
      assert_predicate bin/"{{ .ProjectName }}", :exist?
      system "{{ .ProjectName }}", "--help"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: Command line client for OpenSLO schema files
    caveats: |
      Thank you for installing the command line client for OpenSLO!

      To see help and a list of available commands type:
        $ {{ .ProjectName }} help

      For more information on how to use the command-line client
      and the Nobl9 managed cloud service, visit:
        https://github.com/OpenSLO/oslo
    license: "Apache-2.0"
