name: BATS tests
on:
  pull_request:
jobs:
  batsTests:
    name: lint
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install bats
        run: make install/bats
      - name: Install bats dependencies
        run: make install/bats/dependencies
      - name: Run tests
        run: make run/bats/tests
